format = """
$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$username\
$sudo\
$character\
"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$jobs\
$status\
$os\
$container\
$battery\
$time\
"""

add_newline = true

[character]
format = "$symbol "
success_symbol = "[󰞷](bold blue)"
error_symbol = "[](purple)"

[env_var.VIMSHELL] # vim subshell
format = "[$env_value]($style)"
style = 'green'

[username]
style_user = "yellow bold"
style_root = "purple bold"
format = "[$user]($style) ▻ "
disabled = false

[directory]
home_symbol = ""
truncation_length = 2
truncation_symbol = " "
read_only = " 󰌾"
format = ' [$path]($style)[$read_only]($read_only_style)'

[cmd_duration]
min_time = 500
format = "[$duration ](bright-yellow)"

[jobs]
format = "[ $symbol$number]($style)"
style = "white"
symbol = "[▶ ](blue)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed white"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "[█](green)"
charging_symbol = "[↑](green)"
discharging_symbol = "[↓]()"
unknown_symbol = "[░]()"
empty_symbol = "[▃](red)"

[[battery.display]]
threshold = 40
style = "dimmed yellow"

[[battery.display]]
threshold = 70
style = "dimmed white"

[git_branch]
format = "[ $symbol $branch(:$remote_branch)]($style)"
symbol = "[](bold 5)"
style = "bold 5"

[git_status]
style = "fg:5"
# format = """([$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style))"""
# conflicted = "󱃟"
ahead = "${count}"
behind = "${count}"
# diverged = "[${ahead_count}${behind_count}](cyan)"
# untracked = "◌◦"
# stashed = " "
# modified = " "
# staged = "󰕒"
renamed = "R"
# deleted = "[✕](red)"

[deno]
format = " deno [∫ $version](blue)"
version_format = "${major}.${minor}"

[lua]
format = " [${symbol}${version}]($style)"
symbol = " "
style = "bright-yellow"

[nodejs]
format = " [${symbol}($version)](green)"
symbol = " "
detect_files = ["package-lock.json", "yarn.lock"]
# version_format = "${major}.${minor}"

[python]
format = " [${symbol}${version}]($style)"
symbol = "[](bright-blue) "
version_format = "${major}.${minor}"
style = "bright-yellow"

[ruby]
format = " [${symbol}${version}]($style)"
symbol = " "
version_format = "${major}.${minor}"
style = "red"

[rust]
format = " [$symbol$version]($style)"
symbol = " "
version_format = "${major}.${minor}"
style = "red"

[package]
format = " [$symbol$version]($style)"
version_format = "${major}.${minor}"
symbol = "󰏗 "
style = "bright-yellow"

[swift]
format = " sw [${symbol}${version}]($style)"
symbol = "◁ "
style = "bright-red"
version_format = "${major}.${minor}"

[aws]
format = " aws [$symbol $profile $region]($style)"
style = "blue"
symbol = "  "

[buf]
symbol = " "
format = " [$symbol$version $buf_version]($style)"

[c]
symbol = " "
format = " $symbol($version(-$name))]($style)"

[conda]
symbol = " "
format = " [$symbol$environment]($style)"

[dart]
symbol = " "
format = " [$symbol($version )]($style)"

[docker_context]
symbol = " "
format = " [$symbol$context]($style)"

[elixir]
symbol = " "
format = " [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = " "
format = " [$symbol($version )]($style)"

[golang]
symbol = " "
format = " [$symbol($version )]($style)"

[haskell]
symbol = " "
format = " [$symbol($version )]($style)"

[java]
symbol = " "
format = " [${symbol}(${version} )]($style)"

[julia]
symbol = " "
format = " [$symbol($version )]($style)"

[memory_usage]
symbol = "󰍛 "
format = " [${ram}( ${swap})]($style)"

[nim]
symbol = "󰆥 "
format = " [$symbol($version )]($style)"

[nix_shell]
symbol = " "
format = " [$symbol$state $name]($style)"

[spack]
symbol = "◇ "
format = " spack [$symbol$environment]($style)"

[os]
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
